### ISSUE TITLE
Support for running inside a Docker container

### ISSUE THREAD

**Issue by iRazvan2745** [FZnachor/Uptime-Status#2]
Hello, I'm trying to run this application using Docker and Docker Compose, but I'm encountering issues. I've also tried running it without Docker normally, but it still doesn't work.

Here are the files I’m using:

### Dockerfile

```Dockerfile
# Use the official PHP image with CLI (Command-Line Interface)
FROM php:8.2-cli

# Install required PHP extensions and dependencies
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    unzip \
    git \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_mysql

# Install Composer globally
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Set working directory inside the container
WORKDIR /var/www/html

# Copy the application files into the container
COPY . .

# Install PHP dependencies using Composer
RUN composer install

# Expose port 8000 for the PHP server
EXPOSE 8000

# Command to start the PHP built-in web server
CMD ["php", "-S", "0.0.0.0:8000", "-t", "public"]
```

### docker-compose.yml

```yaml
version: '3.8'

services:
  web:
    build: .
    container_name: uptime-status
    ports:
      - "8000:8000"  # Map container's port 8000 to host's port 8000
    volumes:
      - .:/var/www/html  # Mount the project directory into the container
    environment:
      - VIRTUAL_HOST=uptime-status.local  # Optional, for local DNS mapping
    networks:
      - uptime-status-network

networks:
  uptime-status-network:
    driver: bridge
```

---

### Steps to Reproduce:

1. Clone or download the repository with the Dockerfile and `docker-compose.yml`.
2. Run the following command to build and start the container:

   ```bash
   docker-compose up --build
   ```

3. After the container is built and started, you should be able to access the application via `http://localhost:8000` on your web browser.

---

### Troubleshooting:

If the application is still not working, here are a few things you can check:

- **Check Logs:** You can check the logs of the container by running:

   ```bash
   docker-compose logs web
   ```

   This may provide more information on what's failing inside the container.

- **Network Connectivity:** Make sure that there is no firewall or network issue blocking the connection between your host machine and the container.

---

### Discord Help Request:

I would really appreciate it if someone could help me set this up on Discord for further assistance (and possibly screen share).

---

### Notes

- **Port Mapping:** In the Docker Compose file, I’m mapping the container's port `8000` to the host's port `8000` so you can access the app on `localhost:8000`.
  
- **Local DNS:** The `VIRTUAL_HOST=uptime-status.local` environment variable is optional and is used when you're setting up a local DNS entry like `uptime-status.local` for easier access. This requires additional setup in your `/etc/hosts` file.

---

If anyone has suggestions or solutions, it would be greatly appreciated!

---

**Comment by FZnachor** [comment]
Hello, I have published [Docker image](https://hub.docker.com/r/codespacecz/uptime-status) for Uptime Status to Docker Hub. Bellow is an example `docker-compose.yml` file. Make sure to copy `config.inc.php` file to the config directory and adjust it to your needs.

```
services:
  uptime-status:
    image: codespacecz/uptime-status:latest
    container_name: uptime-status
    ports:
      - "8000:8000"
    volumes:
      - ./config:/var/www/html/config:ro
```
